### ISSUE TITLE
Wrong @SerializedName in V1CredentialXxxRequest

### ISSUE THREAD

**Issue by hhuber1** [hyperledger-labs/acapy-java-client#1]
Dear developers,
we are using the Bosch Aca-py client to build a controller that connects to another agent and issues a credential to that agent.
When using `V1CredentialOfferRequest.java` to call the method `issueCredentialSendOffer` on `AriesClient` we encounter a problem with the serialization of this object to JSON.
From the specification [Hyperledger Aries RFC 0036](https://github.com/hyperledger/aries-rfcs/tree/master/features/0036-issue-credential) it is expected that the credential definition id contained in the request should be serialized to `cred_def_id` but in `V1CredentialOfferRequest.java` the code says
```
    @SerializedName(value = CredDefId.CREDENTIAL_DEFINITION_ID, alternate = CredDefId.CRED_DEF_ID)
    private String credentialDefinitionId;
```
which means that the credential definition id will be serialized to a JSON attribute with key `credential_definition_id`.
(Same for  `V1CredentialProposalRequest`).

Currently, we patched these classes locally but this is not a solution, of course.
Please let us know how to proceed.

Thanks in advance,
Hans.

**Comment by etschelp** [comment]
I have fixed it in the main branch, but haven't created a release yet. I will do this once I merge the 0.7.0-pre.3 changes. If you need something urgently I can create a patch release for you.
