### ISSUE TITLE
Cannot use DID Exchange between multitenant wallets

### ISSUE THREAD

**Issue by tdiesler** [hyperledger-labs/acapy-java-client#23]
After we successfully tackled [RFC 0160: Connection Protocol with multitenant wallets](/hyperledger-labs/acapy-java-client/issues/19 ), I'd like to move on to [RFC 0023: DID Exchange Protocol 1.0](https://github.com/hyperledger/aries-rfcs/tree/main/features/0023-did-exchange).

The idea is that Alice (who does not have a public DID) wants to establish a connection with Faber. 
Here is what I [have so far](https://github.com/tdiesler/nessus-aries/blob/next/itests/smoke/src/test/java/io/nessus/aries/test/DidExchangeTest.java#L35) ...

```
ConnectionRecord aliceRecord = alice.didExchangeCreateRequest(DidExchangeCreateRequestFilter.builder()
        .theirPublicDid(faberPublicDid.getDid())
        .myEndpoint(ACAPY_USER_URL)
        .myLabel("Alice/Faber")
        .build()).get();
log.info("Alice: {}", aliceRecord);

assertConnectionState(aliceWallet, ConnectionState.REQUEST);

/* Faber receives the request
 * 
 * Fails: DIDXRequest.DIDXThread not initialised ???
 * 
faber.didExchangeReceiveRequest(DIDXRequest.builder()
        .id(connectionRecord.getRequestId())
        .label("Alice/Faber") // label required, but not part of Alice's record
        //.did("Alice's DID ???")
        //.type("???")
        //.didDocAttach(???)
        .build(), DidExchangeReceiveRequestFilter.builder()
            .autoAccept(true)
            .build()).get();
*/

/* Alice accepts connection request
 * 
 * Fails with code=404 message=Record not found
alice.didExchangeAcceptRequest(aliceConnectionId, DidExchangeAcceptRequestFilter.builder().build()).get();
 */

/* Faber accepts the request
 *
 * Fails, because Faber does not (yet) have a connection id
 faber.didExchangeAcceptRequest(faberConnectionId, null);
 */
```

Acapy is [started](https://github.com/tdiesler/nessus-aries/tree/next#run-acapy-in-multitenant-mode) with `--auto-ping-connection` and `--auto-accept-requests`

**Comment by etschelp** [comment]
DidExchange works different. If you use receive request both wallets need to have an endpoint on the ledger. So the flow should be:

- alice.didExchangeCreateRequest()
- faber receives connection event 
- faber accepts the connection request
- alice connection state changes to active

**Comment by tdiesler** [comment]
It seems that the ping event is not what we expect

```
2022-04-11 17:05:50 INFO  [io.nessus.aries.test.did_exchange.DidExchangeTest] - WebSocket Message: {"topic": "ping", "authenticated": false}
2022-04-11 17:05:50 ERROR [org.hyperledger.aries.webhook.EventHandler] - Error in webhook event handler:
java.lang.NullPointerException: json is marked non-null but is null
	at org.hyperledger.aries.webhook.EventParser.parseValueSave(EventParser.java:41) ~[aries-client-python-0.7.23.jar:?]
	at org.hyperledger.aries.webhook.EventHandler.handleEvent(EventHandler.java:54) [aries-client-python-0.7.23.jar:?]
	at io.nessus.aries.test.did_exchange.DidExchangeTest$1.onMessage(DidExchangeTest.java:127) [test-classes/:?]
```

I'm also receiving a `settings` event that isn't handled at all

```
2022-04-11 17:05:15 INFO  [io.nessus.aries.test.did_exchange.DidExchangeTest] - WebSocket Message: {"topic": "settings", "payload": {"authenticated": false, "label": "Aries Cloud Agent", "endpoint": "http://localhost:8030", "no_receive_invites": false, "help_link": null}}
2022-04-11 17:05:15 ERROR [io.nessus.aries.test.did_exchange.DidExchangeTest] - JsonSyntaxException
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 35 path $.payload
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226) ~[gson-2.8.6.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.6.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:897) ~[gson-2.8.6.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:846) ~[gson-2.8.6.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:817) ~[gson-2.8.6.jar:?]
	at io.nessus.aries.test.did_exchange.DidExchangeTest$1.onMessage(DidExchangeTest.java:125) [test-classes/:?]
```

Code is [here](https://github.com/tdiesler/nessus-aries/blob/next/itests/smoke/src/test/java/io/nessus/aries/test/did_exchange/DidExchangeTest.java#L51)

BTW, thanks for your continuous feedback. Please stay with me, at the end I'll do a step-by-step write up for the Alice-Faber-Acme walkthrough using this API. Folks coming after this, should have an easier on-ramp.

**Comment by etschelp** [comment]
I did not use the websocket messages so far, so you are finding the issues :) I thought there is a quick fix, but it seems the messages are mutable so I need more testing. But you can help me for example by writing your own WebsocketMessage class that handles a bit more cases like:

```java
@Data @NoArgsConstructor
public class WebsocketMessage {

    private static final Gson gson = GsonConfig.defaultConfig();

    private String topic;
    private Boolean authenticated;
    private JsonObject payload;

    public String getPayloadAsString() {
        return payload != null ? payload.toString() : null;
    }

    public static WebsocketMessage fromMessage(@NonNull String message) {
        return gson.fromJson(message, WebsocketMessage.class);
    }
}
```

Then use it like 
```java
            public void onMessage(WebSocket webSocket, String message) {
                    WebsocketMessage msg = WebsocketMessage.fromMessage(message);
                    handler.handleEvent(msg.getTopic(), msg.getPayload());
            }
```

and test if this already covers all cases. If this works than I will add the changes to the client.

That the ping message has no body seems to be an issue of the websocket message within aca-py and probably needs a ticket in that repo as the client can not do anything about it. I do not want to ignore/catch the exception that is thrown in that case, because it really is an illegal state.

**Comment by tdiesler** [comment]
Hang on, I deleted that comment because WS events need to be handled per wallet. I investigate this a little more before I can comment again.

**Comment by tdiesler** [comment]
I looked at this a little more and tried to implement the connection workflow with websocket events. Generally, it is not clear to me how this is supposed to work. If controllerA (i.e. a client of walletA) asynchronously sends stuff to the agent, it must then either be possible to poll state changes for walletA or have some listening mechanism for walletA events. Webhooks could be such a notification mechanism, but i don't think that clients should generally be required to create http endpoints - a phone for example cannot do that (a web socket connection from the client to the agent makes sense).

Perhaps clientA needs to connect to some sub-wallet specific url and not to `ws://localhost:8031/ws` where we see general base wallet events.

Also, does the agent make calls to potentially another agents (multitenant or not)? For example, as a result from stuff being sent to walletA, should we expect to see state changes in walletB that the client of walletB can poll or be notified about?

**Comment by tdiesler** [comment]
It has to do with proper authentication on the WebSocket - then I see the sub-wallet events. There are still some issues with the client - I'll do a PR for that.

BTW, thanks for your continuous feedback. Please stay with me, at the end I'll do a step-by-step write up for the Alice-Faber-Acme walkthrough using this API. Folks coming after this, should have an easier on-ramp.

**Comment by tdiesler** [comment]
Closing as out-of-date for now. While plowing through the [Aries Agent Test Harness ](https://github.com/hyperledger/aries-agent-test-harness) we will likely encounter issues that can be backed by actual test scenarios
