### ISSUE TITLE
RevocationRegistryState should return values in lower case with toString method

### ISSUE THREAD

**Issue by hhuber1** [hyperledger-labs/acapy-java-client#3]
Hello,
I got an error message when calling `revocationRegistriesCreated(credDefId, RevocationRegistryState.ACTIVE)` on `AriesClient`.
The error message said that only states in lower case are expected.
I patched `RevocationRegistryState` locally with
```
    ACTIVE {
    	@Override
    	public String toString() {
    		return "active";
    	}
    },
```
and it worked.
I suggest to add that kind of a `toString()` method to all enumeration entries.

**Comment by etschelp** [comment]
Fixed with 0.7.0-pre.3.2
