### ISSUE TITLE
Consider using enum instead of string for RevocationEvent.state

### ISSUE THREAD

**Issue by tdiesler** [hyperledger-labs/acapy-java-client#47]
... assuming those states are defined (couldn't find information about that). So far, I see `state=revoked`

```
Alice: [@Acme] issuer_cred_rev RevocationEvent(state=revoked, createdAt=2022-04-27T10:22:21.856908Z, revRegId=KfUGQ8cJceaRiBfBeAAjYv:4:KfUGQ8cJceaRiBfBeAAjYv:3:CL:434:default:CL_ACCUM:3718e227-92e5-446f-8e8e-68c88d92218e, recordId=cbcb26ff-35ed-4f6e-a16d-26d9b0648609, credDefId=KfUGQ8cJceaRiBfBeAAjYv:3:CL:434:default, credExId=89106a4d-09d6-4876-8a40-5849f8efe9cf, uploadedAt=null, credRevId=1)
```

**Comment by tdiesler** [comment]
Aren't these two independent issues? We can have an enum in the java client (unless its really meant to be free text). On the ACA-Py side, it could perhaps also be improved if needed.

If the model switches from string to enum, would that change the json representation?

**Comment by etschelp** [comment]
no it won't, only issue is if aca-py sends other values then deserialisation will fail. i have switched this to enum anyway: https://github.com/hyperledger-labs/acapy-java-client/pull/49
