### ISSUE TITLE
`rfc23Sate` instead of `rfc23State` a mistake? 

### ISSUE THREAD

**Issue by MajdT51** [hyperledger-labs/acapy-java-client#74]
Hello,

Is there a reason why the property called `rfc23Sate` instead of `rfc23State` in [ConnectionRecord](https://github.com/hyperledger-labs/acapy-java-client/blob/main/src/main/java/org/hyperledger/aries/api/connection/ConnectionRecord.java)  ?

Thanks

**Comment by etschelp** [comment]
Nice catch. If people start using the rfc state as well, it would make sense to make it an enum like the `state`
