### ISSUE TITLE
Webhook Documentation is wrong or deprecated

### ISSUE THREAD

**Issue by MajdT51** [hyperledger-labs/acapy-java-client#75]
I think the correct rest endpoint for a webhook must be `@Post("/webhook/topic/{topic}")` otherwise I'm getting a **NotFound** Error in Acapy

<img width="870" alt="image" src="https://user-images.githubusercontent.com/50261972/205091557-916d4c02-556a-41a0-9641-c09da931cd55.png">

From the Webhook [Docs](https://github.com/hyperledger/aries-cloudagent-python/blob/main/AdminAPI.md#administration-api-webhooks) of Acapy:

> When a webhook is dispatched, the record topic is appended as a path component to the URL, for example: https://webhook.host.example becomes https://webhook.host.example/topic/connections when a connection record is updated"

**Comment by etschelp** [comment]
Yap, you are right the /topic part was missing
