### ISSUE TITLE
Support extended VerifiableCredential

### ISSUE THREAD

**Issue by MajdT51** [hyperledger-labs/acapy-java-client#82]
A Verifiable Credential could have extra properties as described in https://www.w3.org/TR/vc-data-model/#extensibility .
Example: 
```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://carla.dih-cloud.com/chained-credential-v1.jsonld",
    "https://carla.dih-cloud.com/participant-credential-v1.jsonld"
  ],
  "credentialSubject": {
    "participantDetails": {
      "name": "string"
    },
    "identityDetails": {
      "did": "did:sov:ArqouCjqi4RwBXQqjAbQrG",
      "uniqueIds": [
        {
          "type": "TEST",
          "value": "100"
        }
      ]
    },
    "id": "did:sov:ArqouCjqi4RwBXQqjAbQrG"
  },
  "provenanceProof": [
    {
      "algorithm": "RSA_RAW",
      "value": [
        "bbbbnmWPldib7jnG2k1TN0fTCtX........gvvLs="
      ]
    }
  ],
  "id": "urn:uuid:23711187-dec1-4bf6-2227-55710f977333",
  "issuanceDate": "2019-12-03T12:19:52Z",
  "issuer": "did:sov:7rB93fLvW5kgujZ4E57ZxL",
  "type": [
    "VerifiableCredential",
    "ParticipantCredential",
    "ChainedCredential"
  ]
}
```
When I need to extract the issued credential from the exchange record I use this method `credExRecord.resolveLDCredential().credential`.  However, the class [VerifiableCredential](https://github.com/hyperledger-labs/acapy-java-client/blob/0.7.33/src/main/java/org/hyperledger/aries/api/jsonld/VerifiableCredential.java) supports no extra properties (in my case provenanceProof) and it get removed without any warning

From Discord chat
 etschelp: "As the provenanceProof is a proof and not the credentialSubject it will not be returned with .credential() ,as it is one node further up in the structure. The client library currently only supports retrieving custom credentialSubjects, and is based on a not extended VerifiableCredential otherwise. What you need is basically to extend the VerifiableCredential.class model on your end and then pass it on as a type to the client when retrieving or creating v2 ld credentials or proofs. This is doable but requires some reworking of the client's api."

**Comment by etschelp** [comment]
See this PR: https://github.com/hyperledger-labs/acapy-java-client/pull/83 for a quick workaround. I guess you probably need this everywhere where a `VerifiableCredential.class` or `VerifiablePresentation.class` is used, here it gets more complicated as this means making all references generic.

**Comment by etschelp** [comment]
Obsolete
