### ISSUE TITLE
Constructing `SendPresentationRequest` with predicates

### ISSUE THREAD

**Issue by miroslav-inc** [hyperledger-labs/acapy-java-client#86]
I'm trying to construct `SendPresentationRequest` with `predicates` but only properties that I can set are 

    public static final class IndyRequestedCredsRequestedPred {
        private String credId;
        private Integer timestamp;
    }

shouldn't this predicate have operator (<,>,<=,>=) and value (20)

**Comment by etschelp** [comment]
I believe what you are looking for is either

a. verifier sending proof request to prover

`presentProofSendRequest(PresentProofRequest proofRequest)` 

or b. prover initiating presentation exchange by starting with:

`presentProofSendProposal(PresentProofProposal proofProposal)`

`IndyRequestedCredsRequestedPred` is part of the manual flow where the prover decides which wallet credentials should be put into the response when answering a proof request.

**Comment by etschelp** [comment]
Closing as the question was answered above
